class AdvisoryCategory < ApplicationRecord
  # belongs_to :aircraft_type
  # belongs_to :category
  belongs_to :advisory_reason

  Fields = {
    ac_configuration: 1,
    ac_location: 2,
    ac_on_ground: 3,
    ac_registry: 4,
    ac_status_datetime: 5,
    acu_problem: 6,
    air_bourne: 7,
    aircraft_type_id: 8,
    apu_inoperative: 9,
    baggage_cargo_loaded: 10,
    blocked_in: 11,
    cabin_crew_boarded: 12,
    category_id: 13,
    close_door: 14,
    cockpit_crew_boarded: 15,
    effective_date: 16,
    flight_date: 17,
    flight_number: 18,
    frequencies: 19,
    general_boarding: 20,
    load_b: 21,
    load_e: 22,
    load_p: 23,
    location: 24,
    max_wind: 25,
    movement: 26,
    no_avi: 27,
    nsta: 28,
    nstd: 29,
    push_back: 30,
    remarks: 31,
    restriction: 32,
    route_destination: 33,
    route_origin: 34,
    seat_blocks: 35,
    sta: 36,
    std: 37,
    tow_in: 38,
    tow_out: 39,
    weather_forecast: 40,
    arrival_terminal: 41,
    departure_terminal: 42,
    duration_of_delay: 43,
    eta: 44,
    etd: 45,
    neta: 46,
    netd: 47,
    pax: 48,
    touchdown: 49
  }.freeze
end
